path_config_file: "../../traffic-imc-dataset/configs/config_mice.yaml"

run:
  name_key: "mice"
  code: 0
  seed: null

datamodule:
  train_val_split: 0.8
  in_steps: 24
  out_steps: 1
  batch_size: 64
  num_workers: 0
  shuffle_training: true
  scale_method: "normal"
  target_sensors: null

model:
  input_dim: 1
  output_dim: 1
  rnn_units: 64
  num_layers: 2
  embed_dim: 10
  cheb_k: 2
  learning_rate: 0.003
  weight_decay: 0.0
  scheduler_step_size: 5
  scheduler_gamma: 0.7
  loss_func: "mse"

early_stopping:
  enabled: true
  patience: 15

trainer:
  max_epochs: 100
  gradient_clip_val: 5.0
