path_config_file: "../../traffic-imc-dataset/configs/config_mice.yaml"

run:
  name_key: "mice"
  code: 0
  seed: null

datamodule:
  train_val_split: 0.8
  seq_len: 24
  horizon: 1
  batch_size: 64
  num_workers: 0
  shuffle_training: true
  add_time_in_day: true
  add_day_in_week: false

model:
  rnn_units: 64
  num_rnn_layers: 2
  max_diffusion_step: 2
  filter_type: "dual_random_walk"
  use_curriculum_learning: true
  cl_decay_steps: 2000
  learning_rate: 0.001
  weight_decay: 0.0
  scheduler_milestones: [20, 30, 40, 50]
  scheduler_gamma: 0.1

early_stopping:
  enabled: true
  patience: 10

trainer:
  max_epochs: 20
  gradient_clip_val: 1.0
