path_config_file: "../../traffic-imc-dataset/configs/config_mice.yaml"

run:
  name_key: "mice"
  code: 0
  seed: null

datamodule:
  train_val_split: 0.8
  seq_length: 24
  batch_size: 512
  num_workers: 0
  shuffle_training: true

model:
  input_size: 1
  hidden_size: 64
  num_layers: 2
  output_size: 1
  learning_rate: 0.001
  dropout_rate: 0.2
  scheduler_factor: 0.5
  scheduler_patience: 10

early_stopping:
  enabled: true
  patience: 5

trainer:
  max_epochs: 20
  gradient_clip_val: 1.0
